version: "3.9"
services:
  web: 
    image: nginx:1.16.1
    container_name: php-test-web
    restart: always
    ports:
      - "4000:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
      - mysql

  php-fpm:
    build: ./php/
    container_name: php-test-fpm
    restart: always
    environment:
      - GREETING=hello
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql:5.7
    container_name: php-test-db
    restart: always
    volumes:
      - ./db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes_from:
      - mysql-data
    command: "true"

  mysql-data:
    image: mysql:5.7
    container_name: php-test-db-container
    volumes:
      - ./db/data:/var/lib/mysql
    command: "true"